name = "reader"
main = "src/index.ts"
compatibility_date = "2023-01-20"
usage_model = "bundled"
kv_namespaces = [
    { binding = "READER_KV", id = "9d591a1d972149698e2460cafbb6feb4", preview_id = "9d591a1d972149698e2460cafbb6feb4"}
]

[triggers]
crons = ["0 */6 * * *"]

[site]
bucket = "./assets"

[vars]
WORKERS_ENV = "prod"